version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
    networks:
      oam:
        ipv6_address: 2001::11
      nr1:
        ipv6_address: 2001:aaaa:aaaa::2
      nr5:
        ipv6_address: 2001:aaaa:aaaa:5::2
      nr9:
        ipv6_address: 2001:aaaa:aaaa:9::2
          
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10023:2606
    networks:
      oam:
        ipv6_address: 2001::12
      nr2:
        ipv6_address: 2001:bbbb:bbbb::2
      nr6:
        ipv6_address: 2001:aaaa:aaaa:6::2
      nr10:
        ipv6_address: 2001:aaaa:aaaa:a::2

  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10031:2601
      #ospf
      - 10032:2604
      #ospf ipv6
      - 10033:2606
    networks:
      nr5:
        ipv6_address: 2001:aaaa:aaaa:5::3

  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10041:2601
      #ospf
      - 10042:2604
      #ospf ipv6
      - 10043:2606
    networks:
      nr6:
        ipv6_address: 2001:aaaa:aaaa:6::3

  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10051:2601
      #ospf
      - 10052:2604
      #ospf ipv6
      - 10053:2606
    networks:
      nr1:
        ipv6_address: 2001:aaaa:aaaa::3
      nr3:
        ipv6_address: 2001:aaaa:aaaa:3::2
      nr7:
        ipv6_address: 2001:aaaa:aaaa:7::2

  r6:
    build: .
    volumes:
      - ./volumes/quagga/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r6/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10061:2601
      #ospf
      - 10062:2604
      #ospf ipv6
      - 10063:2606
    networks:
      nr2:
        ipv6_address: 2001:bbbb:bbbb::3
      nr4:
        ipv6_address: 2001:aaaa:aaaa:4::2
      nr8:
        ipv6_address: 2001:aaaa:aaaa:8::2

  r7:
    build: .
    volumes:
      - ./volumes/quagga/r7/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r7/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r7/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10071:2601
      #ospf
      - 10072:2604
      #ospf ipv6
      - 10073:2606
    networks:
      nr9:
        ipv6_address: 2001:aaaa:aaaa:9::3
      nr11:
        ipv6_address: 2001:aaaa:aaaa:b::2
      nr7:
        ipv6_address: 2001:aaaa:aaaa:7::3

  r8:
    build: .
    volumes:
      - ./volumes/quagga/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r8/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10081:2601
      #ospf
      - 10082:2604
      #ospf ipv6
      - 10083:2606
    networks:
      nr8:
        ipv6_address: 2001:aaaa:aaaa:8::3
      nr10:
        ipv6_address: 2001:aaaa:aaaa:a::3
      nr12:
        ipv6_address: 2001:aaaa:aaaa:c::2

  h11:
    build: .
    volumes:
      - ./volumes/quagga/h11/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/h11/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/h11/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10111:2601
      #ospf
      - 10112:2604
      #ospf ipv6
      - 10113:2606
    networks:
      nr3:
        ipv6_address: 2001:aaaa:aaaa:3::3

  h12:
    build: .
    volumes:
      - ./volumes/quagga/h12/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/h12/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/h12/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10121:2601
      #ospf
      - 10122:2604
      #ospf ipv6
      - 10123:2606
    networks:
      nr4:
        ipv6_address: 2001:aaaa:aaaa:4::3

  h13:
    build: .
    volumes:
      - ./volumes/quagga/h13/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/h13/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/h13/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10131:2601
      #ospf
      - 10132:2604
      #ospf ipv6
      - 10133:2606
    networks:
      nr11:
        ipv6_address: 2001:aaaa:aaaa:b::3

  h14:
    build: .
    volumes:
      - ./volumes/quagga/h14/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/h14/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/h14/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10141:2601
      #ospf
      - 10142:2604
      #ospf ipv6
      - 10143:2606
    networks:
      nr12:
        ipv6_address: 2001:aaaa:aaaa:c::3
  
networks:
  oam:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001::/64
  nr1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa::/64
  nr2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb::/64
  nr3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:3::/64
  nr4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:4::/64
  nr5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:5::/64
  nr6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:6::/64
  nr7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:7::/64
  nr8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:8::/64
  nr9:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:9::/64
  nr10:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:a::/64
  nr11:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:b::/64
  nr12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa:c::/64


