version: '2.1'

services:
  b1:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10101:2601
      #ospf ipv6
      - 10103:2606
      #bgp
      - 10104:2605
    networks:
      red2:
        ipv6_address: 2001:a:2::10
      red3:
        ipv6_address: 2001:a:3::10
      red4:
        ipv6_address: 2001:a:4::10
      redb12:
        ipv6_address: 2001:b:12::10
      redb13:
        ipv6_address: 2001:b:13::10

  b2:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
    networks:
      red12:
        ipv6_address: 2001:a:12::10
      red13:
        ipv6_address: 2001:a:13::10
      red14:
        ipv6_address: 2001:a:14::10
      redb12:
        ipv6_address: 2001:b:12::20
      redb32:
        ipv6_address: 2001:b:32::10

  b3:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b3/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10301:2601
      #ospf ipv6
      - 10303:2606
      #bgp
      - 10304:2605
    networks:
      red9:
        ipv6_address: 2001:a:9::10
      redb13:
        ipv6_address: 2001:b:13::20
      redb32:
        ipv6_address: 2001:b:32::20

  r3:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10013:2601
      #ospf ipv6
      - 10033:2606
    networks:
      red2:
        ipv6_address: 2001:a:2::20
          
  r4:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10014:2601
      #ospf ipv6
      - 10034:2606
    networks:
      red12:
        ipv6_address: 2001:a:12::20

  r5:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10015:2601
      #ospf ipv6
      - 10035:2606
    networks:
      red3:
        ipv6_address: 2001:a:3::20
      red5:
        ipv6_address: 2001:a:5::10
      red7:
        ipv6_address: 2001:a:7::10

  r6:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10016:2601
      #ospf ipv6
      - 10036:2606
    networks:
      red13:
        ipv6_address: 2001:a:13::20
      red15:
        ipv6_address: 2001:a:15::10
      red17:
        ipv6_address: 2001:a:17::10

  r7:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r7/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r7/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10017:2601
      #ospf ipv6
      - 10037:2606
    networks:
      red4:
        ipv6_address: 2001:a:4::20
      red6:
        ipv6_address: 2001:a:6::10
      red7:
        ipv6_address: 2001:a:7::20

  r8:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10018:2601
      #ospf ipv6
      - 10038:2606
    networks:
      red14:
        ipv6_address: 2001:a:14::20
      red16:
        ipv6_address: 2001:a:16::10
      red17:
        ipv6_address: 2001:a:17::20

  r9:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r9/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r9/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10019:2601
      #ospf ipv6
      - 10039:2606
    networks:
      red9:
        ipv6_address: 2001:a:9::20

  h11:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10020:2601
      #ospf ipv6
      - 10040:2606
    networks:
      red5:
        ipv6_address: 2001:a:5::20

  h12:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf ipv6
      - 10041:2606
    networks:
      red15:
        ipv6_address: 2001:a:15::20

  h13:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10022:2601
      #ospf ipv6
      - 10042:2606
    networks:
      red6:
        ipv6_address: 2001:a:6::20

  h14:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10023:2601
      #ospf ipv6
      - 10043:2606
    networks:
      red16:
        ipv6_address: 2001:a:16::20


networks:
  red2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:2::/64
  red3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:3::/64
  red4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:4::/64
  red5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:5::/64
  red6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:6::/64
  red7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:7::/64
  red9:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:9::/64
  red12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:12::/64
  red13:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:13::/64
  red14:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:14::/64
  red15:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:15::/64
  red16:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:16::/64
  red17:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a:17::/64
  redb12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b:12::/64
  redb13:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b:13::/64
  redb32:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b:32::/64
